"""Parsing and ordering helpers for the deliberately free-form CV date fields."""

from __future__ import annotations

import calendar
import re
from datetime import date
from typing import Any, Mapping


UNKNOWN_CV_DATE = (9999, 12, 31)

_MONTH_NAMES = {
    name.casefold(): number
    for number in range(1, 13)
    for name in (calendar.month_name[number], calendar.month_abbr[number])
}


def _four_digit_year(value: str) -> int:
    year = int(value)
    if year < 100:
        return year + (2000 if year < 40 else 1900)
    return year


def _valid_date(year: int, month: int = 1, day: int = 1) -> tuple[int, int, int]:
    try:
        parsed = date(year, month, day)
    except ValueError:
        return UNKNOWN_CV_DATE
    return (parsed.year, parsed.month, parsed.day)


def cv_date_sort_key(value: Any) -> tuple[int, int, int]:
    """Return the beginning of a CV date or date range as a sortable value.

    CV dates remain untouched for display. The parser only supplies a chronological
    key and accepts the formats generated by imports and manual editing.
    """

    text = str(value or "").strip().rstrip(",")
    if not text:
        return UNKNOWN_CV_DATE

    match = re.match(r"^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})(?:\D|$)", text)
    if match:
        return _valid_date(int(match.group(1)), int(match.group(2)), int(match.group(3)))

    match = re.match(r"^(\d{1,2})/(\d{1,2})/(\d{2}|\d{4})(?:\D|$)", text)
    if match:
        return _valid_date(_four_digit_year(match.group(3)), int(match.group(1)), int(match.group(2)))

    match = re.match(r"^(\d{1,2})\.(\d{1,2})\.(\d{2}|\d{4})(?:\D|$)", text)
    if match:
        return _valid_date(_four_digit_year(match.group(3)), int(match.group(2)), int(match.group(1)))

    match = re.match(r"^(\d{1,2})[/.](\d{4})(?:\D|$)", text)
    if match:
        return _valid_date(int(match.group(2)), int(match.group(1)))

    match = re.match(r"^(\d{4})[-/.](\d{1,2})(?:\D|$)", text)
    if match:
        return _valid_date(int(match.group(1)), int(match.group(2)))

    month_pattern = "|".join(sorted(_MONTH_NAMES, key=len, reverse=True))
    match = re.match(
        rf"^({month_pattern})\s+(?:(\d{{1,2}})(?:st|nd|rd|th)?[,]?\s+)?(\d{{4}})(?:\D|$)",
        text.casefold(),
    )
    if match:
        return _valid_date(int(match.group(3)), _MONTH_NAMES[match.group(1)], int(match.group(2) or 1))

    match = re.match(r"^(\d{4})(?:\D|$)", text)
    if match:
        return _valid_date(int(match.group(1)))

    return UNKNOWN_CV_DATE


def cv_entry_sort_key(row: Mapping[str, Any]) -> tuple[str, tuple[int, int, int], tuple[int, int, int], int]:
    """Order entry mappings chronologically within their database section."""

    try:
        row_id = int(row.get("id") or 0)
    except (TypeError, ValueError):
        row_id = 0
    return (
        str(row.get("section_key") or ""),
        cv_date_sort_key(row.get("start_date")),
        cv_date_sort_key(row.get("end_date")),
        row_id,
    )
